# Server configuration
server:
  port: 8080
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s

# Database configuration
database:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: trytrago_dev
  max_open_conns: 50
  max_idle_conns: 10
  conn_lifetime: 5m

# Logging configuration
logging:
  level: debug  # debug, info, warn, error
  format: console  # json or console
  output: stdout
  file_path: ""

# Authentication configuration
auth:
  jwt_secret: your-development-secret-key
  access_token_duration: 1h
  refresh_token_duration: 168h  # 7 days

# Cache configuration
cache:
  type: redis
  address: localhost:6379
  password: ""
  db: 0
  ttl: 10m

# Environment
environment: development
